export const SET_NAME='SET_NAME';
export const SET_PHONE='SET_PHONE';
export const SET_EMAIL='SET_EMAIL';
export const SET_COMPANY_NAME='SET_COMPANY_NAME';


export const SET_PICKUP_ADDRESS='SET_PICKUP_ADDRESS';
export const SET_PICKUP_PIN='SET_PICKUP_PIN';
export const SET_DESTINATION_ADDRESS='SET_DESTINATION_ADDRESS';
export const SET_DESTINATION_PIN='SET_DESTINATION_PIN';

export const SET_NUMBER_OF_UNITS='SET_NUMBER_OF_UNITS';
export const SET_WEIGHT_PER_UNIT='SET_WEIGHT_PER_UNIT';
export const SET_UNIT='SET_UNIT';
export const SET_HEIGHT='SET_HEIGHT';
export const SET_WIDTH='SET_WIDTH';
export const SET_LENGTH='SET_LENGTH';

export const RESET_STATE='RESET_STATE';